version: '3'
name: "${APP_NAME}-${APP_ENV}"

services:
  server:
    image: "node:21"
    container_name: "${APP_NAME}-${APP_ENV}-server"
    ports: [ "${PORT_FRONT_HTTP}:80", "${PORT_FRONT_HTTPS}:443" ]
    volumes:
      - ".:/home/docker:ro"
    working_dir: "/home/docker"
    command: "npm start"

  build:
    image: "node:18"
    container_name: "${APP_NAME}-${APP_ENV}-build"
    user: "1000"
    environment:
      - "FONTAWESOME_NPM_AUTH_TOKEN=${FONTAWESOME_NPM_AUTH_TOKEN}"
      - "PORT_WEBPACK=${PORT_WEBPACK}"
    ports:
      - "${PORT_WEBPACK}:${PORT_WEBPACK}"
    tty: true #to have color in terminal when log
    working_dir: "/home/node"
    volumes:
      - "./docker/build:/home/docker"
      - "./:/home/node"
    command: "npm run serve"
    restart: "on-failure"
